"""Streamlit UI for the ModuleWarden Underwriter Assistant.

Run:

    streamlit run chat/app.py

The UI is intentionally simple: a chat thread, a sidebar listing
available incidents with one-click insertion into the prompt, an
expandable structured-evidence panel that shows the router decision
for the most recent answer, and a session reset button.

The verdict is always pinned by the deterministic gate. When a fine-tuned
model endpoint is configured (MW_MODEL_ENDPOINT_BASE_URL + _API_KEY +
_MODEL, or OPENAI_API_KEY), the assistant additionally narrates that
pinned verdict in underwriter language using the live model. The
title-bar badge shows which mode is active so the live-model moment is
visible on stage.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

try:
    import streamlit as st
except ImportError as exc:  # pragma: no cover - documented requirement
    raise SystemExit(
        "Streamlit is required to run chat/app.py: pip install streamlit"
    ) from exc

from chat.agent import _list_incidents, handle_query, lookup_by_incident_id
from chat import model_client

st.set_page_config(
    page_title="ModuleWarden Underwriter Assistant",
    page_icon=":shield:",
    layout="wide",
)


# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------


if "messages" not in st.session_state:
    st.session_state.messages = [
        {
            "role": "assistant",
            "content": (
                "Hi -- I am the ModuleWarden Underwriter Assistant.\n\n"
                "Ask me about an npm package and version (for example "
                "`postmark-mcp@1.0.16`), ask `what are the gate rules?` "
                "to walk the deterministic policy, or ask `help` for "
                "the full menu."
            ),
        }
    ]
    st.session_state.last_evidence = {}


# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------


with st.sidebar:
    st.markdown("### ModuleWarden")
    st.caption("Conversational risk briefing for cyber-policy underwriters")
    st.markdown("---")
    st.markdown("**Try one of these:**")
    for incident in _list_incidents():
        if st.button(f"audit {incident}", key=f"btn_{incident}", use_container_width=True):
            st.session_state.messages.append(
                {"role": "user", "content": f"look up {incident}"}
            )
            # Direct id lookup; no regex round-trip and no
            # package-name reconstruction. The previous
            # implementation built `lodash-4.17.21@4.17.21` for
            # single-token package names and silently fell into
            # lookup_unknown.
            turn = lookup_by_incident_id(incident)
            st.session_state.messages.append(
                {"role": "assistant", "content": turn.response_md}
            )
            st.session_state.last_evidence = turn.evidence
            st.rerun()

    st.markdown("---")
    st.markdown("**Suggested questions:**")
    for q in [
        "what are the gate rules?",
        "list incidents",
        "help",
    ]:
        if st.button(q, key=f"q_{q}", use_container_width=True):
            st.session_state.messages.append({"role": "user", "content": q})
            turn = handle_query(q, history=st.session_state.messages)
            st.session_state.messages.append(
                {"role": "assistant", "content": turn.response_md}
            )
            st.session_state.last_evidence = turn.evidence
            st.rerun()

    st.markdown("---")
    if st.button("Reset session", use_container_width=True):
        st.session_state.messages = st.session_state.messages[:1]
        st.session_state.last_evidence = {}
        st.rerun()


# ---------------------------------------------------------------------------
# Main column
# ---------------------------------------------------------------------------


st.title(":shield: ModuleWarden Underwriter Assistant")
st.caption(
    "A UNIQA cyber-policy underwriter assesses an applicant's npm "
    "dependency risk in plain language. The verdict is pinned by the "
    "ModuleWarden gate; the fine-tuned model narrates it as an "
    "underwriting decision."
)
_cfg = model_client.resolve_config()
if _cfg is not None:
    st.success(
        f"Live model: backed by `{_cfg.model}` via {_cfg.source} endpoint. "
        "Replies are generated by the fine-tuned model over the pinned verdict."
    )
else:
    st.info(
        "Deterministic mode: no model endpoint configured. Verdicts and the "
        "Control Evidence Memo are exact; set MW_MODEL_ENDPOINT_BASE_URL "
        "(+_API_KEY/_MODEL) or OPENAI_API_KEY to add live model narration."
    )

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])


prompt = st.chat_input(
    "Ask about a package, a gate rule, or a historical incident..."
)
if prompt:
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)
    turn = handle_query(prompt, history=st.session_state.messages)
    st.session_state.messages.append(
        {"role": "assistant", "content": turn.response_md}
    )
    st.session_state.last_evidence = turn.evidence
    with st.chat_message("assistant"):
        st.markdown(turn.response_md)


# ---------------------------------------------------------------------------
# Evidence panel
# ---------------------------------------------------------------------------


if st.session_state.last_evidence:
    ev = st.session_state.last_evidence
    label = "Structured evidence (machine-readable)"
    if ev.get("model_backed"):
        label += " - model-backed reply"
    elif ev.get("endpoint_error"):
        label += " - model endpoint error (showing deterministic memo)"
    with st.expander(label, expanded=False):
        st.json(ev)
