import { readFileSync } from 'node:fs';
import { load as parseYaml } from 'js-yaml';

/**
 * Parsed entry from any supported lockfile format.
 */
export interface LockfileEntry {
  packageName: string;
  version: string;
  integrity: string;
  resolved?: string;
  dev?: boolean;
  optional?: boolean;
  dependencies?: string[];
}

/**
 * Result of parsing a lockfile.
 */
export interface LockfileParseResult {
  format: 'npm' | 'pnpm' | 'yarn';
  entries: LockfileEntry[];
  errors: string[];
}

/**
 * Parse a lockfile from its file path.
 * Detects format by filename.
 */
export function parseLockfile(filePath: string): LockfileParseResult {
  const content = readFileSync(filePath, 'utf-8');
  const filename = filePath.split('/').pop()?.toLowerCase() ?? '';
  const format = detectLockfileFormat(content) ?? undefined;
  return parseLockfileContent(content, format, filename);
}

/**
 * Parse a lockfile from its content.
 * Detects format from content if not specified.
 */
export function parseLockfileContent(
  content: string,
  format?: string,
  filename?: string
): LockfileParseResult {
  const detected = format ?? detectLockfileFormat(content) ?? guessFormatFromFilename(filename);

  switch (detected) {
    case 'npm':
      return parseNpmLockfileContent(content);
    case 'pnpm':
      return parsePnpmLockfileContent(content);
    case 'yarn':
      return parseYarnLockfileContent(content);
    default:
      return {
        format: 'npm',
        entries: [],
        errors: [`Unrecognized lockfile format${filename ? `: ${filename}` : ''}`],
      };
  }
}

function guessFormatFromFilename(filename?: string): string | null {
  if (!filename) return null;
  const lower = filename.toLowerCase();
  if (lower === 'package-lock.json') return 'npm';
  if (lower === 'pnpm-lock.yaml' || lower === 'pnpm-lock.yml') return 'pnpm';
  if (lower === 'yarn.lock') return 'yarn';
  return null;
}

/**
 * Detect lockfile format from content.
 */
export function detectLockfileFormat(content: string): 'npm' | 'pnpm' | 'yarn' | null {
  if (content.trim().startsWith('{')) return 'npm';
  if (content.includes('lockfileVersion:')) return 'pnpm';
  if (content.includes('# THIS IS AN AUTOGENERATED FILE')) return 'yarn';
  if (content.includes('# yarn lockfile')) return 'yarn';
  return null;
}

// ── npm package-lock.json parser (content-based) ────────────

function parseNpmLockfileContent(content: string): LockfileParseResult {
  const errors: string[] = [];
  const entries: LockfileEntry[] = [];

  try {
    const lock = JSON.parse(content);

    if (!lock.packages && !lock.dependencies) {
      errors.push('npm lockfile has no packages or dependencies entries');
      return { format: 'npm', entries: [], errors };
    }

    // npm v7+ uses "packages" (flat node_modules tree)
    if (lock.packages) {
      for (const [pkgPath, rawInfo] of Object.entries(lock.packages)) {
        const info = rawInfo as Record<string, any>;
        // Skip root package and workspace references
        if (pkgPath === '' || pkgPath.startsWith('node_modules/.package')) continue;

        const packageName = pkgPath.replace(/^node_modules\//, '');
        if (!info.version || !packageName) continue;
        if (packageName.startsWith('@')) {
          // Scoped packages: @scope/name
          const parts = packageName.split('/');
          if (parts.length < 2) continue;
        }

        const dependencies = info.dependencies ? Object.keys(info.dependencies) : undefined;
        entries.push({
          packageName,
          version: info.version,
          integrity: info.integrity ?? '',
          ...(info.resolved !== undefined ? { resolved: info.resolved } : {}),
          dev: info.dev ?? false,
          optional: info.optional ?? false,
          ...(dependencies ? { dependencies } : {}),
        });
      }
    }

    // npm v6 uses "dependencies" (nested tree)
    if (lock.dependencies && !lock.packages) {
      flattenNpmDependencies(lock.dependencies, entries);
    }
  } catch (err) {
    errors.push(`Failed to parse npm lockfile: ${err instanceof Error ? err.message : String(err)}`);
  }

  return { format: 'npm', entries, errors };
}

function flattenNpmDependencies(
  deps: Record<string, any>,
  entries: LockfileEntry[],
  parent?: string
): void {
  for (const [name, info] of Object.entries(deps)) {
    const resolvedName = parent ? `${parent}/node_modules/${name.split('/').pop()}` : name;
    if (info.version) {
      entries.push({
        packageName: resolvedName,
        version: info.version,
        integrity: info.integrity ?? '',
        ...(info.resolved !== undefined ? { resolved: info.resolved } : {}),
        dev: info.dev ?? false,
        optional: info.optional ?? false,
      });
    }
    if (info.dependencies) {
      flattenNpmDependencies(info.dependencies, entries, resolvedName);
    }
  }
}

// ── pnpm pnpm-lock.yaml parser (content-based + v9 support) ─

function parsePnpmLockfileContent(content: string): LockfileParseResult {
  const errors: string[] = [];
  const entries: LockfileEntry[] = [];

  try {
    const lock = parseYaml(content) as Record<string, any> | null;

    if (!lock?.packages) {
      errors.push('pnpm lockfile has no packages entry');
      return { format: 'pnpm', entries: [], errors };
    }

    // pnpm packages key format:
    //   v5/v6: /package-name@version  (leading slash)
    //   v9:    package-name@version    (no leading slash for unscoped)
    //          /@scope/name@version     (leading slash for scoped)
    for (const [key, rawInfo] of Object.entries(lock.packages)) {
      const info = rawInfo as Record<string, any>;
      // Skip package group entries
      if (!key) continue;

      // Parse: [/]package-name@version or [/]@scope/name@version
      const match = key.match(/^\/?((?:@[^/]+\/)?[^@/]+)@(.+)$/);
      if (!match) continue;

      const packageName = match[1];
      const version = match[2];
      if (!packageName || !version) continue;

      // Extract integrity from resolution
      const resolution = info.resolution ?? {};
      const integrity = resolution.integrity ?? '';

      const dependencies = info.dependencies ? Object.keys(info.dependencies) : undefined;
      entries.push({
        packageName,
        version,
        integrity,
        dev: info.dev ?? false,
        optional: info.optional ?? false,
        ...(dependencies ? { dependencies } : {}),
      });
    }
  } catch (err) {
    errors.push(`Failed to parse pnpm lockfile: ${err instanceof Error ? err.message : String(err)}`);
  }

  return { format: 'pnpm', entries, errors };
}

// ── yarn.lock parser (content-based) ────────────────────────

function parseYarnLockfileContent(content: string): LockfileParseResult {
  const errors: string[] = [];
  const entries: LockfileEntry[] = [];

  try {
    // Yarn lockfile format: blocks separated by blank lines
    // Each block starts with a quoted package name specifier
    // e.g., "package-name@^1.0.0":
    //   version "1.0.0"
    //   integrity sha512-...
    const blocks = content.split(/\n\n(?!\s+)/);
    for (const block of blocks) {
      const lines = block.split('\n').map((l: string) => l.trim()).filter(Boolean);
      if (lines.length < 2) continue;

      // First line: "package-name@version-specifier:"
      const firstLineRaw = lines[0];
      if (!firstLineRaw) continue;
      const firstLine = firstLineRaw.replace(/^"/, '').replace(/":$/, '').replace(/:$/, '');
      const specifierMatch = firstLine.match(/^((?:@[^/]+\/)?[^@]+)@(.+)$/);
      if (!specifierMatch) continue;

      const packageName = specifierMatch[1];
      if (!packageName) continue;

      // Parse YAML-like fields
      let version = '';
      let integrity = '';
      let resolved = '';

      for (const line of lines.slice(1)) {
        if (line.startsWith('version ')) {
          version = line.replace(/^version\s+"?([^"]*)"?$/, '$1').trim();
        } else if (line.startsWith('integrity ')) {
          integrity = line.replace(/^integrity\s+"?([^"]*)"?$/, '$1').trim();
        } else if (line.startsWith('resolved ')) {
          resolved = line.replace(/^resolved\s+"?([^"]*)"?$/, '$1').trim();
        }
      }

      if (packageName && version) {
        entries.push({
          packageName,
          version,
          integrity: integrity || '',
          ...(resolved ? { resolved } : {}),
        });
      }
    }
  } catch (err) {
    errors.push(`Failed to parse yarn lockfile: ${err instanceof Error ? err.message : String(err)}`);
  }

  return { format: 'yarn', entries, errors };
}
