import { describe, it, expect } from 'vitest';
import { writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { parseLockfile } from '../services/lockfile';

function withTempDir(fn: (dir: string) => void) {
  const dir = mkdtempSync(join(tmpdir(), 'lockfile-test-'));
  try {
    fn(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

describe('parseLockfile — npm', () => {
  it('parses npm v7+ lockfile (packages format)', () => {
    withTempDir((dir) => {
      const path = join(dir, 'package-lock.json');
      writeFileSync(path, JSON.stringify({
        name: 'test-project',
        lockfileVersion: 3,
        packages: {
          '': { name: 'test-project' },
          'node_modules/lodash': {
            version: '4.17.21',
            integrity: 'sha512-hash-lodash',
            resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz',
          },
          'node_modules/express': {
            version: '4.18.2',
            integrity: 'sha512-hash-express',
            dependencies: { accepts: '1.3.8' },
          },
        },
      }, null, 2));

      const result = parseLockfile(path);
      expect(result.format).toBe('npm');
      expect(result.entries).toHaveLength(2);
      expect(result.entries[0].packageName).toBe('lodash');
      expect(result.entries[0].version).toBe('4.17.21');
      expect(result.entries[1].packageName).toBe('express');
      expect(result.entries[1].version).toBe('4.18.2');
    });
  });

  it('parses npm v6 lockfile (dependencies format)', () => {
    withTempDir((dir) => {
      const path = join(dir, 'package-lock.json');
      writeFileSync(path, JSON.stringify({
        name: 'test',
        version: '1.0.0',
        lockfileVersion: 1,
        dependencies: {
          lodash: {
            version: '4.17.21',
            integrity: 'sha512-hash-lodash',
          },
        },
      }, null, 2));

      const result = parseLockfile(path);
      expect(result.entries).toHaveLength(1);
      expect(result.entries[0].packageName).toBe('lodash');
    });
  });

  it('handles empty or malformed npm lockfiles', () => {
    withTempDir((dir) => {
      const path = join(dir, 'package-lock.json');
      writeFileSync(path, 'not valid json');

      const result = parseLockfile(path);
      expect(result.errors.length).toBeGreaterThan(0);
      expect(result.entries).toHaveLength(0);
    });
  });
});

describe('parseLockfile — pnpm', () => {
  it('parses pnpm lockfile with packages', () => {
    withTempDir((dir) => {
      const path = join(dir, 'pnpm-lock.yaml');
      writeFileSync(path, [
        "lockfileVersion: '6.0'",
        '',
        'packages:',
        '  /lodash@4.17.21:',
        '    resolution:',
        '      integrity: sha512-hash-lodash',
        '    dev: false',
        '  /express@4.18.2:',
        '    resolution:',
        '      integrity: sha512-hash-express',
        '    dependencies:',
        '      accepts: 1.3.8',
        '',
      ].join('\n'));

      const result = parseLockfile(path);
      expect(result.format).toBe('pnpm');
      expect(result.entries).toHaveLength(2);
      expect(result.entries[0].packageName).toBe('lodash');
      expect(result.entries[0].version).toBe('4.17.21');
      expect(result.entries[1].packageName).toBe('express');
      expect(result.entries[1].version).toBe('4.18.2');
    });
  });
});

describe('parseLockfile — yarn', () => {
  it('parses yarn.lock format', () => {
    withTempDir((dir) => {
      const path = join(dir, 'yarn.lock');
      writeFileSync(path, [
        '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
        '# yarn lockfile v1',
        '',
        'lodash@^4.17.21:',
        '  version "4.17.21"',
        '  integrity sha512-hash-lodash',
        '  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"',
        '',
        'express@^4.18.0:',
        '  version "4.18.2"',
        '  integrity sha512-hash-express',
        '',
      ].join('\n'));

      const result = parseLockfile(path);
      expect(result.format).toBe('yarn');
      expect(result.entries).toHaveLength(2);
      expect(result.entries[0].packageName).toBe('lodash');
      expect(result.entries[0].version).toBe('4.17.21');
    });
  });
});

describe('parseLockfile — detection', () => {
  it('rejects unknown filename', () => {
    withTempDir((dir) => {
      const path = join(dir, 'unknown.lock');
      writeFileSync(path, '{}');

      const result = parseLockfile(path);
      expect(result.errors.length).toBeGreaterThan(0);
      expect(result.entries).toHaveLength(0);
    });
  });
});
